CREATE TABLE IF NOT EXISTS game_logs (
    game_id VARCHAR(50),
    team_id INT,
    season_id INT,
    game_date DATE,
    matchup VARCHAR(255),
    wl VARCHAR(2),
    min INT,
    pts INT,
    fgm INT,
    fga INT,
    fg3m INT,
    fg3a INT,
    ftm INT,
    fta INT,
    oreb INT,
    dreb INT,
    reb INT,
    ast INT,
    stl INT,
    blk INT,
    tov INT,
    pf INT,
    plus_minus DOUBLE PRECISION,
    PRIMARY KEY (game_id, team_id)
);
