CREATE TABLE IF NOT EXISTS boxscores (
    game_id VARCHAR(50),
    team_id INT,
    player_id INT,
    start_position VARCHAR(10),
    comment TEXT,
    min DOUBLE PRECISION,
    fgm INT,
    fga INT,
    fg3m INT,
    fg3a INT,
    ftm INT,
    fta INT,
    oreb INT,
    dreb INT,
    reb INT,
    ast INT,
    stl INT,
    blk INT,
    turnovers INT,
    pf INT,
    pts INT,
    plus_minus INT,
    PRIMARY KEY (game_id, player_id)
);